# PYTHON PROGRAMMING

## 1. COMMENTS

1. Comments can be used to explain Python code.
2. Comments can be used to make the code more readable.
3. Comments can be used to prevent execution when testing code.

Comments starts with a #, and Python will ignore them:

#This is a comment

print("Hello, World!")

In [1]:
print("Hello, World!")
print("Hello, World2!")

Hello, World!
Hello, World2!


In [4]:
2*2

4

## 2. CREATING VARIABLES

Variables are containers for storing data values.

Unlike other programming languages, Python has no command for declaring a variable.

A variable is created the moment you first assign a value to it.

EXAMPLE:

x = 5

y = "John"

print(x)

print(y)

In [ ]:
x = 2

In [ ]:
d = "Arsalan "
e = "Grade B"

print (d+e)

In [ ]:
for x in range (1,11):
    q= 2*x
    print ("2 x " + str(x) + " = " + str(q))

## 3. LIST

A list is a collection which is ordered and changeable. In Python lists are written with square brackets.

##### SIMPLE LIST:

thislist = ["apple", "banana", "cherry"] <br>
print(thislist)


In [ ]:
vowels = ['a','e','i','o','u']
vowels

In [ ]:
thislist = ["apple", "banana", "cherry"]
thislist

##### NESTED LIST (LIST OF LISTS):

Also, a list can even have another list as an item. This is called nested list.

thislist = ["mouse", [8, 4, 6], ['a']]<br>
print(thislist)

In [ ]:
thislist = ["mouse", [8, 4, 6], ['a']]
print(thislist)

In [ ]:
colors = ['blue','green','black',[1,2,3,4,5],'red','orange']
colors

### (a) Access Items

You access the list items by referring to the index number:

EXAMPLE:

thislist = ["apple", "banana", "cherry"]

print(thislist[1])

In [ ]:
colors[1]

In [ ]:
colors[4]

### (b) Negative Indexing

Negative indexing means beginning from the end, -1 refers to the last item, -2 refers to the second last item etc.

EXAMPLE:

thislist = ["apple", "banana", "cherry"]

print(thislist[-1])

In [ ]:
alphabet = ['a','b','c','d','e','f','g','h','i','j']
alphabet[-1]

### (c) Range of Indexes

You can specify a range of indexes by specifying where to start and where to end the range.

When specifying a range, the return value will be a new list with the specified items.

##### EXAMPLE:

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]

print(thislist[2:5])

In [2]:
colors[2:5]

C:\Users\Engr Zainab Lakho\AppData\Roaming\Python\Python311\site-packages\IPython\core\magics\basic.py:347: UserWarning: Error changing shell color schemes.
The 'colors' trait of a ZMQInteractiveShell instance expected any of ['Neutral', 'NoColor', 'LightBG', 'Linux'] (case-insensitive), not the str '[2:5]'.
  color_switch_err('shell')
C:\Users\Engr Zainab Lakho\AppData\Roaming\Python\Python311\site-packages\IPython\core\magics\basic.py:354: UserWarning: Error changing exception color schemes.
Unrecognized color scheme: [2:5]
Valid schemes: ['NoColor', 'Linux', 'LightBG', 'Neutral', '']
  color_switch_err('exception')
C:\Users\Engr Zainab Lakho\AppData\Roaming\Python\Python311\site-packages\IPython\core\magics\basic.py:361: UserWarning: Error changing object inspector color schemes.
Unrecognized color scheme: [2:5]
Valid schemes: ['NoColor', 'Linux', 'LightBG', 'Neutral', '']
  color_switch_err('object inspector')


In [ ]:
colors[2:-2]

### (d) Change Item Value

To change the value of a specific item, refer to the index number:

##### EXAMPLE:

thislist = ["apple", "banana", "cherry"] <br>
thislist[1] = "blackcurrant" <br>
print(thislist)<br>

In [ ]:
alphabet = ['a','b','c','d','e','f','g','h','i','j']
alphabet[4] = 'z'
alphabet

### (e) Add Items

To add an item to the end of the list, use the append() method:

##### EXAMPLE:

thislist = ["apple", "banana", "cherry"] <br>
thislist.append("orange")<br>
print(thislist)<br>

In [ ]:
alphabet[4] = 'z'
alphabet.append('k')
alphabet

### (f) Extend Method

##### EXAMPLE:

list1 = ["a", "b" , "c"]<br>
list2 = [1, 2, 3]<br>

list1.extend(list2)<br>
print(list1)<br>

In [ ]:
alphabet2 = ['k','l','m','n','o']
alphabet.extend(alphabet2)
alphabet

### (g) Copy a List

You cannot copy a list simply by typing list2 = list1, because: list2 will only be a reference to list1, and changes made in list1 will automatically also be made in list2.

There are ways to make a copy, one way is to use the built-in List method copy().

##### EXAMPLE:
thislist = ["apple", "banana", "cherry"]<br>
mylist = thislist.copy()<br>
print(mylist)

In [ ]:
alphabet1 = ['a','b','c','d','e','f','g','h','i','j']
alphabet2 = alphabet1.copy()
alphabet2

## 4. TUPLES

A tuple is a collection which is ordered and unchangeable. In Python tuples are written with round brackets.

### DIFFERENCE BETWEEN LISTS AND TUPLES:

The main difference between lists and a tuples is the fact that lists are mutable whereas tuples are immutable. A mutable data type means that a python object of this type can be modified. An immutable object can't.

##### EXAMPLE:

thistuple = ("apple", "banana", "cherry")<br>
print(thistuple)

In [ ]:
alphabet1 = ('a','b','c','d','e','f','g','h','i','j')

### (a) Access Tuple Items

You can access tuple items by referring to the index number, inside square brackets:<br>
thistuple = ("apple", "banana", "cherry")<br>
print(thistuple[1])

In [ ]:
alphabet1[0]

In [ ]:
alphabet1[0] = 'h'

# 5. PYTHON MODULES

## (A) Numpy

* Numpy is the backbone of Machine Learning in Python.
* It is one of the most important libraries in Python for numerical computations.
* It adds support to core Python for multi-dimensional arrays (and matrices) and fast vectorized operations on these arrays.

##### EXAMPLE:

import numpy as np

arr = np.array([1,3,4,5,6])

print(arr)

In [ ]:
import numpy as np

arr = np.array([1,3,4,5,6])

print(arr)

In [ ]:
arr.shape

arr = np.arange(10)

In [4]:
import numpy as np
arr= np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr[5:]

array([5, 6, 7, 8, 9])

In [6]:
arr[5:8]

array([5, 6, 7])

In [7]:
arr[:-5]

array([0, 1, 2, 3, 4])

In [8]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### np.ones():
Creates a matrix of specified dimension containing only ones.

##### EXAMPLE:
arr = np.ones((2,4))<BR>
print(arr)

In [ ]:
arr = np.ones((2,4))
print(arr)

### np.zeros():
Creates a matrix of specified dimensions containing only zeroes.

##### EXAMPLE:
c = np.zeros([3, 3]) <BR>
print(c)

In [ ]:
import numpy
c = numpy.zeros((3, 3))
print(c)

### np.random
By using the randn function from the numpy.random package an array of a specified dimension can be initialized with random values.

##### EXAMPLE:
arr = np.random.randn(3,4)
arr

In [ ]:
arr = np.random.randn(3,4)
print(arr)


### MATRIX OPERATIONS:

import numpy<br>
#### Two matrices are initialized by value
x = numpy.array([[1, 2], [4, 5]])<br>
y = numpy.array([[7, 8], [9, 10]])<br>
####  add() is used to add matrices
print ("Addition of two matrices: ")<br>
print (numpy.add(x,y))<br>
#### subtract() is used to subtract matrices
print ("Subtraction of two matrices : ")<br>
print (numpy.subtract(x,y))<br>
#### divide() is used to divide matrices
print ("Matrix Division : ")<br>
print (numpy.divide(x,y))<br>
#### multiply() is used to multiply matrices
print ("Multiplication of two matrices: ")<br>
print (numpy.multiply(x,y))<br>
#### using "T" to transpose the matrix
print ("Matrix transposition : ")<br>
print (x.T)<br>

In [ ]:
import numpy
#Two matrices are initialized by value
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

#add() is used to add matrices
print ("Addition of two matrices: ")
print (numpy.add(x,y))

#subtract() is used to subtract matrices
print ("Subtraction of two matrices : ")
print (numpy.subtract(x,y))

#divide() is used to divide matrices
print ("Matrix Division : ")
print (numpy.divide(x,y))

#multiply() is used to multiply matrices
print ("Multiplication of two matrices: ")
print (numpy.multiply(x,y))

#using "T" to transpose the matrix
print ("Matrix transposition : ")
print (x.T)

## (B) PANDAS

### CSV files to dataframe
> CSV (Comma Separated Files) files are perhaps one of the most widely used ways of creating a dataframe. We can easily read in a CSV, or any delimited file (like TSV), using pandas and convert into a dataframe.

data = pd.read_csv('Data.csv')

data

In [ ]:
import pandas as pd
data = pd.read_csv('Data.csv')
data

### Selecting pandas data using “iloc”

The iloc indexer for Pandas Dataframe is used for integer-location based indexing / selection by position.

The iloc indexer syntax is data.iloc[<row selection>, <column selection>], which is sure to be a source of confusion for R users. “iloc” in pandas is used to select rows and columns by number, in the order that they appear in the data frame. You can imagine that each row has a row number from 0 to the total rows (data.shape[0])  and iloc[] allows selections based on these numbers. The same applies for columns (ranging from 0 to data.shape[1] )

There are two “arguments” to iloc – a row selector, and a column selector.  For example:

### Single selections using iloc and DataFrame

##### Rows:
data.iloc[0] # first row of data frame <br>
data.iloc[1] # second row of data frame <br>
data.iloc[-1] # last row of data frame <br>
###### Columns:
data.iloc[:,0] # first column of data frame <br>
data.iloc[:,1] # second column of data frame <br>
data.iloc[:,-1] # last column of data frame <br>

In [ ]:
data.iloc[:,-1] # last column of data frame

### Multiple row and column selections using iloc and DataFrame
data.iloc[0:5] # first five rows of  <br>
data.iloc[:, 0:2] # first two columns of data frame with all rows <br>
data.iloc[[0,3,6,24], [0,5,6]] # 1st, 4th, 7th, 25th row + 1st 6th 7th columns. <br>
data.iloc[0:5, 5:8] # first 5 rows and 5th, 6th, 7th columns of data frame (county -> phone1).

In [ ]:
data.iloc[0:5] # first five rows of

In [ ]:
data.iloc[:, 0:2] # first two columns of data frame with all rows

In [ ]:
data

In [ ]:
data.iloc[[0,3,6],[0,2]] # 1st, 4th, 7th row + 1st 4th columns.

In [ ]:
data.iloc[0:5, 1:3] # first 5 rows and 2nd, 3rd, 4th columns of data frame.

## (C) Matplotlib

Matplotlib is one of the most popular Python packages used for data visualization. It is a cross-platform library for making 2D plots from data in arrays. It provides an object-oriented API that helps in embedding plots in applications using Python GUI toolkits such as PyQt, WxPythonotTkinter. It can be used in Python and IPython shells, Jupyter notebook and web application servers also.

Run the following command:

%matplotlib inline

In [ ]:
%matplotlib inline

##### EXAMPLE

import numpy as np <br>
from matplotlib import pyplot as plt <br>

x = np.arange(1,11) <br>
y = 2 * x + 5 <br>
plt.title("Matplotlib demo") <br>
plt.xlabel("x axis caption") <br>
plt.ylabel("y axis caption") <br>
plt.plot(x,y) <br>
plt.show() <br>

In [9]:
import numpy as np
from matplotlib import pyplot as plt

x = np.arange(1,11)
y = 2 * x + 5
plt.title("Matplotlib demo")
plt.xlabel("x axis caption")
plt.ylabel("y axis caption")
plt.plot(x,y)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'